services:
  # Redis service (local development only)
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - housetracker-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  property-url-discovery-spider:
    environment:
      - SERVICE_ENV=local
      - AWS_PROFILE=${AWS_PROFILE}
    volumes:
      - ~/.aws:/root/.aws:ro
      - ../crawler/redfin_spider/property_url_discovery_spider_logs:/houseTracker/python/crawler/redfin_spider/property_url_discovery_spider_logs

  property-crawler-spider:
    environment:
      - SERVICE_ENV=local
      - AWS_PROFILE=${AWS_PROFILE}
    deploy:
      mode: replicated-job
      replicas: 2  # Run 2 instances
      restart_policy:
        condition: on-failure
    volumes:
      - ~/.aws:/root/.aws:ro
      - ../crawler/redfin_spider/property_crawler_spider_logs:/houseTracker/python/crawler/redfin_spider/property_crawler_spider_logs
      - ../crawler/redfin_spider/property_crawler_spider_output:/houseTracker/python/crawler/redfin_spider/property_crawler_spider_output

  property-data-ingestion-service:
    environment:
      - SERVICE_ENV=local
      - AWS_PROFILE=${AWS_PROFILE}
    volumes:
      - ~/.aws:/root/.aws:ro
      - ../data_service/property_data_ingestion_logs:/houseTracker/python/data_service/property_data_ingestion_logs
