name: housetracker

services:
  # Property URL Discovery Spider
  property-url-discovery-spider:
    build:
      context: ..
      dockerfile: Dockerfile
      target: redfin-spider
    environment:
      - SPIDER_NAME=property_url_discovery_spider
      - SERVICE_ENV=local
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - housetracker-network
    # profiles:
    #   - crawler

  # Property Crawler Spider
  property-crawler-spider:
    build:
      context: ..
      dockerfile: Dockerfile
      target: redfin-spider
    environment:
      - SPIDER_NAME=property_crawler_spider
      - SERVICE_ENV=local
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - housetracker-network
    # profiles:
    #   - crawler

  # Property Data Ingestion Service
  property-data-ingestion-service:
    build:
      context: ..
      dockerfile: Dockerfile
      target: data-ingestion-service
    environment:
      - SERVICE_ENV=local
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - housetracker-network
    # profiles:
    #   - data_ingestion

networks:
  housetracker-network:
    driver: bridge